### ISSUE TITLE
Illustrations might be in CMYK

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/os-why#8]
@kpettinga I'm thinking you've pulled the illustrations straight from the printed assets folder. We might need to re-format these back to RGB.

**Comment by kpettinga** [comment]
@elliotarthur i converted the psd's and re-exported them. i think it's fixed? The PSDs i was sourcing were from the **Holiday Card 2016/Assets/Raw Artwork from Martin/** shared folder.

I made copies to work from inside **Holiday Card 2016/Digital/image sources/**
